spring:
  application:
    name: Arun-Spring-Boot
server:
  compression:
    enabled: true
  port: 61666
management:
  endpoint:
    heapdump:
      enabled: false
    threaddump:
      enabled: false
---
spring:
  profiles: local
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.tool.hbm2ddl: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.cache: trace
    org.springframework.data: debug
    org.springframework.web: debug
trace: false
debug: true
---
spring:
  profiles: h2
  h2:
      console:
        enabled: true
        path: /h2
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    enabled: false
---
spring:
  profiles: amqp
  rabbitmq:
    host: arunmbp-rabbitmq
    port: 5672
---
spring:
  profiles: cassandra
  data:
    cassandra:
      keyspace-name: testcass
      contact-points: arunmbp-cassandra
      port: 9042
      schema-action: create_if_not_exists
      fetch-size: 1000
  flyway:
    enabled: false